name: Test DNS and CDN for miraii.cn

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dns-test:
    runs-on: ubuntu-latest
    steps:
      # 1. 测试 CDN 或 API 响应
      - name: Test CDN/API Response
        run: |
          echo ">>> Start testing your CDN/API"
          curl -I -w "\nTotal time: %{time_total}s\nHTTP Code: %{http_code}\n" -s https://busuanzi.aimiliy.top/api/

      # 2. DNS 基本解析
      - name: Basic DNS Lookup
        run: |
          echo "::group::DNS Lookup (nslookup)"
          nslookup miraii.cn
          echo "::endgroup::"

      # 3. DNS 使用 dig 查询详细信息
      - name: Detailed DNS Info
        run: |
          echo "::group::Detailed DNS Info (dig)"
          dig miraii.cn +short +nocmd
          dig miraii.cn A +short
          dig miraii.cn AAAA +short
          dig miraii.cn CNAME +short
          echo "::endgroup::"

      # 4. 测试最终访问结果
      - name: Test Final HTTP Response
        run: |
          echo "::group::Curl Final Response"
          curl -I -L https://miraii.cn
          echo "::endgroup::"

      # 5. 分地理位置测试（可选）
      - name: Test Resolved IP from Multiple DNS Servers
        run: |
          echo "::group::GeoDNS Check"
          echo "Google DNS:"
          dig @8.8.8.8 miraii.cn +short
          echo "Cloudflare DNS:"
          dig @1.1.1.1 miraii.cn +short
          echo "Aliyun DNS (China):"
          dig @223.5.5.5 miraii.cn +short
          echo "::endgroup::"
